rrt_planner:

  GENERAL:
    timerPeriod:        0.1           # period of path planning task in [s]

  LOCAL:
    goalBias:           0.3   
    goalRadius:         4.0           # acceptance range in [m]
    iterations:         500           # iterations for planning
    maxNumOfNodes:      600           # limits number of nodes in searchtree
    minCost:            0.0           # cost threshold used to filter nodes when tracing back the path to root
    minDeviation:       0.15           # minimum distance (oriented) between close states in [m]
    minDeviationDist:   0.05          # minimum distance between close states in [m]
    psiWeight:          1000          # weight of orientation difference in simulation distance estimation
    resolution:         0.1           # maximum of interpolation steps in [m]
    rewireTime:         2.0           # maximum estimated time in which connection is checked in [simulationTimeStep]
    sampleRange:        4.0           # used for random sampling near the detected cones, range in [m]
    simIterations:      4             # number of iterations of searching closest point on trajectory to goal state
    simulationTimeStep: 0.2           # in [s]
    thetaWeight:        50            # weight of orientation difference in state comparison
    triangleIterations: 1             # number of triangle optimizations in one iteration of planning

  GLOBAL:
    goalBias:           0.0   
    goalRadius:         3.0           # acceptance range in [m]
    iterations:         50            # iterations for planning
    maxNumOfNodes:      9000          # limits number of nodes in searchtree
    minCost:            4.0           # cost threshold used to filter nodes when tracing back the path to root
    minDeviation:       0.2           # minimum distance (oriented) between close states in [m]
    minDeviationDist:   0.05          # minimum distance between close states in [m]
    psiWeight:          1000          # weight of orientation difference in simulation distance estimation
    resolution:         0.1           # maximum of interpolation steps in [m]
    rewireTime:         2.0           # maximum estimated time in which connection is checked in [simulationTimeStep]
    sampleRange:        4.0           # used for random sampling near the detected cones, range in [m]
    simIterations:      4             # number of iterations of searching closest point on trajectory to goal state
    simulationTimeStep: 0.2           # in [s]
    thetaWeight:        1            # weight of orientation difference in state comparison
    triangleIterations: 10            # number of triangle optimizations in one iteration of planning

  VEHICLE:
    maxdDelta:          1.2           # maximum speed of front axis steering angle in [rad/s] 
    maxDelta:           0.38          # maximum front axis steering angle in [rad]
    maxLatAccel:        16            # maximum lateral acceleration in [m/s2]
    maxLongAccel:       12            # maximum longitudinal acceleration in [m/s2]
    maxVelocity:        10            # in [m/s]
    simType:            "KINEMATIC"   # can be "HOLONOMIC", "KINEMATIC" or "DYNAMIC" vehiclemodel
    track:              1.2           # in [m]
    wheelBase:          1.54          # in [m]

  MAP:
    collisionRadius:    0.95          # minimum distance of car and cone in [m]
    goalHorizon:        10            # maximal distance for local goal state in [m]
    maxConeDist:        6             # maximal distance between consecutive cones in [m]
    maxGap:             1.8           # maximum allowed gap between upsampled cones in [m]

  CONTROL:
    kPsi:               2             # proportional gain of psi lateral control in [-]
    kDelta:             5             # poportional gain of steering angle control [1/s] 
